/*
*   Copyright 2012-2013 The Regents of the University of Colorado
*
*   Licensed under the Apache License, Version 2.0 (the "License")
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.21 at 10:33:43 PM EDT 
//


package edu.ucdenver.rosita.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for care_site complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="care_site">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="care_site_source_value" type="{}string_max50"/>
 *         &lt;element name="x_data_source_type" type="{}string_max20"/>
 *         &lt;element name="organization_source_value" type="{}string_max50"/>
 *         &lt;element name="place_of_service_source_value" type="{}string_max50"/>
 *         &lt;element name="x_care_site_name" type="{}string_max50"/>
 *         &lt;element name="care_site_address_1" type="{}string_max50"/>
 *         &lt;element name="care_site_address_2" type="{}string_max50"/>
 *         &lt;element name="care_site_city" type="{}string_max50"/>
 *         &lt;element name="care_site_state" type="{}string_max2"/>
 *         &lt;element name="care_site_zip" type="{}string_max9"/>
 *         &lt;element name="care_site_county" type="{}string_max20"/>
 *         &lt;element name="provider" type="{}provider" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "care_site", propOrder = {
    "careSiteSourceValue",
    "xDataSourceType",
    "organizationSourceValue",
    "placeOfServiceSourceValue",
    "xCareSiteName",
    "careSiteAddress1",
    "careSiteAddress2",
    "careSiteCity",
    "careSiteState",
    "careSiteZip",
    "careSiteCounty",
    "provider"
})
public class CareSite {

    @XmlElement(name = "care_site_source_value", required = true)
    protected String careSiteSourceValue;
    @XmlElement(name = "x_data_source_type", required = true)
    protected String xDataSourceType;
    @XmlElement(name = "organization_source_value", required = true)
    protected String organizationSourceValue;
    @XmlElement(name = "place_of_service_source_value", required = true, nillable = true)
    protected String placeOfServiceSourceValue;
    @XmlElement(name = "x_care_site_name", required = true, nillable = true)
    protected String xCareSiteName;
    @XmlElement(name = "care_site_address_1", required = true, nillable = true)
    protected String careSiteAddress1;
    @XmlElement(name = "care_site_address_2", required = true, nillable = true)
    protected String careSiteAddress2;
    @XmlElement(name = "care_site_city", required = true, nillable = true)
    protected String careSiteCity;
    @XmlElement(name = "care_site_state", required = true, nillable = true)
    protected String careSiteState;
    @XmlElement(name = "care_site_zip", required = true, nillable = true)
    protected String careSiteZip;
    @XmlElement(name = "care_site_county", required = true, nillable = true)
    protected String careSiteCounty;
    protected List<Provider> provider;

    /**
     * Gets the value of the careSiteSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCareSiteSourceValue() {
        return careSiteSourceValue;
    }

    /**
     * Sets the value of the careSiteSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCareSiteSourceValue(String value) {
        this.careSiteSourceValue = value;
    }

    /**
     * Gets the value of the xDataSourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXDataSourceType() {
        return xDataSourceType;
    }

    /**
     * Sets the value of the xDataSourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXDataSourceType(String value) {
        this.xDataSourceType = value;
    }

    /**
     * Gets the value of the organizationSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationSourceValue() {
        return organizationSourceValue;
    }

    /**
     * Sets the value of the organizationSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationSourceValue(String value) {
        this.organizationSourceValue = value;
    }

    /**
     * Gets the value of the placeOfServiceSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceOfServiceSourceValue() {
        return placeOfServiceSourceValue;
    }

    /**
     * Sets the value of the placeOfServiceSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceOfServiceSourceValue(String value) {
        this.placeOfServiceSourceValue = value;
    }

    /**
     * Gets the value of the xCareSiteName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCareSiteName() {
        return xCareSiteName;
    }

    /**
     * Sets the value of the xCareSiteName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCareSiteName(String value) {
        this.xCareSiteName = value;
    }

    /**
     * Gets the value of the careSiteAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCareSiteAddress1() {
        return careSiteAddress1;
    }

    /**
     * Sets the value of the careSiteAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCareSiteAddress1(String value) {
        this.careSiteAddress1 = value;
    }

    /**
     * Gets the value of the careSiteAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCareSiteAddress2() {
        return careSiteAddress2;
    }

    /**
     * Sets the value of the careSiteAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCareSiteAddress2(String value) {
        this.careSiteAddress2 = value;
    }

    /**
     * Gets the value of the careSiteCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCareSiteCity() {
        return careSiteCity;
    }

    /**
     * Sets the value of the careSiteCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCareSiteCity(String value) {
        this.careSiteCity = value;
    }

    /**
     * Gets the value of the careSiteState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCareSiteState() {
        return careSiteState;
    }

    /**
     * Sets the value of the careSiteState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCareSiteState(String value) {
        this.careSiteState = value;
    }

    /**
     * Gets the value of the careSiteZip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCareSiteZip() {
        return careSiteZip;
    }

    /**
     * Sets the value of the careSiteZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCareSiteZip(String value) {
        this.careSiteZip = value;
    }

    /**
     * Gets the value of the careSiteCounty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCareSiteCounty() {
        return careSiteCounty;
    }

    /**
     * Sets the value of the careSiteCounty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCareSiteCounty(String value) {
        this.careSiteCounty = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the provider property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProvider().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Provider }
     * 
     * 
     */
    public List<Provider> getProvider() {
        if (provider == null) {
            provider = new ArrayList<Provider>();
        }
        return this.provider;
    }

}
