/*
*   Copyright 2012-2013 The Regents of the University of Colorado
*
*   Licensed under the Apache License, Version 2.0 (the "License")
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.21 at 10:33:43 PM EDT 
//


package edu.ucdenver.rosita.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for condition_occurrence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="condition_occurrence">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="condition_occurrence_source_identifier" type="{}string_max50"/>
 *         &lt;element name="x_data_source_type" type="{}string_max20"/>
 *         &lt;element name="person_source_value" type="{}string_max50"/>
 *         &lt;element name="condition_source_value" type="{}string_max50"/>
 *         &lt;element name="condition_source_value_vocabulary" type="{}string_max50"/>
 *         &lt;element name="x_condition_source_desc" type="{}string_max50"/>
 *         &lt;element name="condition_start_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="x_condition_update_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="condition_end_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="condition_type_source_value" type="{}string_max50"/>
 *         &lt;element name="stop_reason" type="{}string_max20"/>
 *         &lt;element name="associated_provider_source_value" type="{}string_max50"/>
 *         &lt;element name="visit_occurrence_source_value" type="{}string_max50"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "condition_occurrence", propOrder = {
    "conditionOccurrenceSourceIdentifier",
    "xDataSourceType",
    "personSourceValue",
    "conditionSourceValue",
    "conditionSourceValueVocabulary",
    "xConditionSourceDesc",
    "conditionStartDate",
    "xConditionUpdateDate",
    "conditionEndDate",
    "conditionTypeSourceValue",
    "stopReason",
    "associatedProviderSourceValue",
    "xVisitOccurrenceSourceIdentifier"
})
public class ConditionOccurrence {

    @XmlElement(name = "condition_occurrence_source_identifier", required = true)
    protected String conditionOccurrenceSourceIdentifier;
    @XmlElement(name = "x_data_source_type", required = true)
    protected String xDataSourceType;
    @XmlElement(name = "person_source_value", required = true)
    protected String personSourceValue;
    @XmlElement(name = "condition_source_value", required = true)
    protected String conditionSourceValue;
    @XmlElement(name = "condition_source_value_vocabulary", required = true)
    protected String conditionSourceValueVocabulary;
    @XmlElement(name = "x_condition_source_desc", required = true, nillable = true)
    protected String xConditionSourceDesc;
    @XmlElement(name = "condition_start_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar conditionStartDate;
    @XmlElement(name = "x_condition_update_date", required = true, nillable = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar xConditionUpdateDate;
    @XmlElement(name = "condition_end_date", required = true, nillable = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar conditionEndDate;
    @XmlElement(name = "condition_type_source_value", required = true)
    protected String conditionTypeSourceValue;
    @XmlElement(name = "stop_reason", required = true, nillable = true)
    protected String stopReason;
    @XmlElement(name = "associated_provider_source_value", required = true, nillable = true)
    protected String associatedProviderSourceValue;
    @XmlElement(name = "x_visit_occurrence_source_identifier", required = true, nillable = true)
    protected String xVisitOccurrenceSourceIdentifier;

    /**
     * Gets the value of the conditionOccurrenceSourceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionOccurrenceSourceIdentifier() {
        return conditionOccurrenceSourceIdentifier;
    }

    /**
     * Sets the value of the conditionOccurrenceSourceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionOccurrenceSourceIdentifier(String value) {
        this.conditionOccurrenceSourceIdentifier = value;
    }

    /**
     * Gets the value of the xDataSourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXDataSourceType() {
        return xDataSourceType;
    }

    /**
     * Sets the value of the xDataSourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXDataSourceType(String value) {
        this.xDataSourceType = value;
    }

    /**
     * Gets the value of the personSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonSourceValue() {
        return personSourceValue;
    }

    /**
     * Sets the value of the personSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonSourceValue(String value) {
        this.personSourceValue = value;
    }

    /**
     * Gets the value of the conditionSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionSourceValue() {
        return conditionSourceValue;
    }

    /**
     * Sets the value of the conditionSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionSourceValue(String value) {
        this.conditionSourceValue = value;
    }

    /**
     * Gets the value of the conditionSourceValueVocabulary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionSourceValueVocabulary() {
        return conditionSourceValueVocabulary;
    }

    /**
     * Sets the value of the conditionSourceValueVocabulary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionSourceValueVocabulary(String value) {
        this.conditionSourceValueVocabulary = value;
    }

    /**
     * Gets the value of the xConditionSourceDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXConditionSourceDesc() {
        return xConditionSourceDesc;
    }

    /**
     * Sets the value of the xConditionSourceDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXConditionSourceDesc(String value) {
        this.xConditionSourceDesc = value;
    }

    /**
     * Gets the value of the conditionStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getConditionStartDate() {
        return conditionStartDate;
    }

    /**
     * Sets the value of the conditionStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setConditionStartDate(XMLGregorianCalendar value) {
        this.conditionStartDate = value;
    }

    /**
     * Gets the value of the xConditionUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getXConditionUpdateDate() {
        return xConditionUpdateDate;
    }

    /**
     * Sets the value of the xConditionUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setXConditionUpdateDate(XMLGregorianCalendar value) {
        this.xConditionUpdateDate = value;
    }

    /**
     * Gets the value of the conditionEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getConditionEndDate() {
        return conditionEndDate;
    }

    /**
     * Sets the value of the conditionEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setConditionEndDate(XMLGregorianCalendar value) {
        this.conditionEndDate = value;
    }

    /**
     * Gets the value of the conditionTypeSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionTypeSourceValue() {
        return conditionTypeSourceValue;
    }

    /**
     * Sets the value of the conditionTypeSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionTypeSourceValue(String value) {
        this.conditionTypeSourceValue = value;
    }

    /**
     * Gets the value of the stopReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopReason() {
        return stopReason;
    }

    /**
     * Sets the value of the stopReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopReason(String value) {
        this.stopReason = value;
    }

    /**
     * Gets the value of the associatedProviderSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociatedProviderSourceValue() {
        return associatedProviderSourceValue;
    }

    /**
     * Sets the value of the associatedProviderSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociatedProviderSourceValue(String value) {
        this.associatedProviderSourceValue = value;
    }

    /**
     * Gets the value of the visitOccurrenceSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getxVisitOccurrenceSourceIdentifier() {
        return xVisitOccurrenceSourceIdentifier;
    }

    /**
     * Sets the value of the visitOccurrenceSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setxVisitOccurrenceSourceIdentifier(String value) {
        this.xVisitOccurrenceSourceIdentifier = value;
    }

}
