/*
*   Copyright 2012-2013 The Regents of the University of Colorado
*
*   Licensed under the Apache License, Version 2.0 (the "License")
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.21 at 10:33:43 PM EDT 
//


package edu.ucdenver.rosita.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for death complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="death">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="person_source_value" type="{}string_max50"/>
 *         &lt;element name="death_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="death_type_concept_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="death_type_source_value" type="{}string_max50"/>
 *         &lt;element name="cause_of_death_source_value" type="{}string_max50"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "death", propOrder = {
    "personSourceValue",
    "deathDate",
    "deathTypeConceptId",
    "deathTypeSourceValue",
    "causeOfDeathSourceValue"
})
public class Death {

    @XmlElement(name = "person_source_value", required = true)
    protected String personSourceValue;
    @XmlElement(name = "death_date", required = true, nillable = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deathDate;
    @XmlElement(name = "death_type_concept_id", required = true)
    protected BigInteger deathTypeConceptId;
    @XmlElement(name = "death_type_source_value", required = true, nillable = true)
    protected String deathTypeSourceValue;
    @XmlElement(name = "cause_of_death_source_value", required = true, nillable = true)
    protected String causeOfDeathSourceValue;

    /**
     * Gets the value of the personSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonSourceValue() {
        return personSourceValue;
    }

    /**
     * Sets the value of the personSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonSourceValue(String value) {
        this.personSourceValue = value;
    }

    /**
     * Gets the value of the deathDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeathDate() {
        return deathDate;
    }

    /**
     * Sets the value of the deathDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeathDate(XMLGregorianCalendar value) {
        this.deathDate = value;
    }

    /**
     * Gets the value of the deathTypeConceptId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDeathTypeConceptId() {
        return deathTypeConceptId;
    }

    /**
     * Sets the value of the deathTypeConceptId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDeathTypeConceptId(BigInteger value) {
        this.deathTypeConceptId = value;
    }

    /**
     * Gets the value of the deathTypeSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeathTypeSourceValue() {
        return deathTypeSourceValue;
    }

    /**
     * Sets the value of the deathTypeSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeathTypeSourceValue(String value) {
        this.deathTypeSourceValue = value;
    }

    /**
     * Gets the value of the causeOfDeathSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCauseOfDeathSourceValue() {
        return causeOfDeathSourceValue;
    }

    /**
     * Sets the value of the causeOfDeathSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCauseOfDeathSourceValue(String value) {
        this.causeOfDeathSourceValue = value;
    }

}
