/*
*   Copyright 2012-2013 The Regents of the University of Colorado
*
*   Licensed under the Apache License, Version 2.0 (the "License")
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.21 at 10:33:43 PM EDT 
//


package edu.ucdenver.rosita.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for drug_cost complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="drug_cost">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="drug_cost_source_identifier" type="{}string_max50"/>
 *         &lt;element name="drug_exposure_source_identifier" type="{}string_max50"/>
 *         &lt;element name="paid_copay" type="{}decimal_precision8_scale2"/>
 *         &lt;element name="paid_coinsurance" type="{}decimal_precision8_scale2"/>
 *         &lt;element name="paid_toward_deductible" type="{}decimal_precision8_scale2"/>
 *         &lt;element name="paid_by_payer" type="{}decimal_precision8_scale2"/>
 *         &lt;element name="paid_by_coordination_benefits" type="{}decimal_precision8_scale2"/>
 *         &lt;element name="total_out_of_pocket" type="{}decimal_precision8_scale2"/>
 *         &lt;element name="total_paid" type="{}decimal_precision8_scale2"/>
 *         &lt;element name="ingredient_cost" type="{}decimal_precision8_scale2"/>
 *         &lt;element name="dispensing_fee" type="{}decimal_precision8_scale2"/>
 *         &lt;element name="average_wholesale_price" type="{}decimal_precision8_scale2"/>
 *         &lt;element name="payer_plan_period_source_identifier" type="{}string_max50"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "drug_cost", propOrder = {
    "drugCostSourceIdentifier",
    "drugExposureSourceIdentifier",
    "paidCopay",
    "paidCoinsurance",
    "paidTowardDeductible",
    "paidByPayer",
    "paidByCoordinationBenefits",
    "totalOutOfPocket",
    "totalPaid",
    "ingredientCost",
    "dispensingFee",
    "averageWholesalePrice",
    "payerPlanPeriodSourceIdentifier"
})
public class DrugCost {

    @XmlElement(name = "drug_cost_source_identifier", required = true)
    protected String drugCostSourceIdentifier;
    @XmlElement(name = "drug_exposure_source_identifier", required = true)
    protected String drugExposureSourceIdentifier;
    @XmlElement(name = "paid_copay", required = true, nillable = true)
    protected BigDecimal paidCopay;
    @XmlElement(name = "paid_coinsurance", required = true, nillable = true)
    protected BigDecimal paidCoinsurance;
    @XmlElement(name = "paid_toward_deductible", required = true, nillable = true)
    protected BigDecimal paidTowardDeductible;
    @XmlElement(name = "paid_by_payer", required = true, nillable = true)
    protected BigDecimal paidByPayer;
    @XmlElement(name = "paid_by_coordination_benefits", required = true, nillable = true)
    protected BigDecimal paidByCoordinationBenefits;
    @XmlElement(name = "total_out_of_pocket", required = true, nillable = true)
    protected BigDecimal totalOutOfPocket;
    @XmlElement(name = "total_paid", required = true, nillable = true)
    protected BigDecimal totalPaid;
    @XmlElement(name = "ingredient_cost", required = true, nillable = true)
    protected BigDecimal ingredientCost;
    @XmlElement(name = "dispensing_fee", required = true, nillable = true)
    protected BigDecimal dispensingFee;
    @XmlElement(name = "average_wholesale_price", required = true, nillable = true)
    protected BigDecimal averageWholesalePrice;
    @XmlElement(name = "payer_plan_period_source_identifier", required = true, nillable = true)
    protected String payerPlanPeriodSourceIdentifier;

    /**
     * Gets the value of the drugCostSourceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugCostSourceIdentifier() {
        return drugCostSourceIdentifier;
    }

    /**
     * Sets the value of the drugCostSourceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugCostSourceIdentifier(String value) {
        this.drugCostSourceIdentifier = value;
    }

    /**
     * Gets the value of the drugExposureSourceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugExposureSourceIdentifier() {
        return drugExposureSourceIdentifier;
    }

    /**
     * Sets the value of the drugExposureSourceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugExposureSourceIdentifier(String value) {
        this.drugExposureSourceIdentifier = value;
    }

    /**
     * Gets the value of the paidCopay property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaidCopay() {
        return paidCopay;
    }

    /**
     * Sets the value of the paidCopay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaidCopay(BigDecimal value) {
        this.paidCopay = value;
    }

    /**
     * Gets the value of the paidCoinsurance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaidCoinsurance() {
        return paidCoinsurance;
    }

    /**
     * Sets the value of the paidCoinsurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaidCoinsurance(BigDecimal value) {
        this.paidCoinsurance = value;
    }

    /**
     * Gets the value of the paidTowardDeductible property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaidTowardDeductible() {
        return paidTowardDeductible;
    }

    /**
     * Sets the value of the paidTowardDeductible property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaidTowardDeductible(BigDecimal value) {
        this.paidTowardDeductible = value;
    }

    /**
     * Gets the value of the paidByPayer property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaidByPayer() {
        return paidByPayer;
    }

    /**
     * Sets the value of the paidByPayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaidByPayer(BigDecimal value) {
        this.paidByPayer = value;
    }

    /**
     * Gets the value of the paidByCoordinationBenefits property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaidByCoordinationBenefits() {
        return paidByCoordinationBenefits;
    }

    /**
     * Sets the value of the paidByCoordinationBenefits property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaidByCoordinationBenefits(BigDecimal value) {
        this.paidByCoordinationBenefits = value;
    }

    /**
     * Gets the value of the totalOutOfPocket property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalOutOfPocket() {
        return totalOutOfPocket;
    }

    /**
     * Sets the value of the totalOutOfPocket property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalOutOfPocket(BigDecimal value) {
        this.totalOutOfPocket = value;
    }

    /**
     * Gets the value of the totalPaid property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalPaid() {
        return totalPaid;
    }

    /**
     * Sets the value of the totalPaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalPaid(BigDecimal value) {
        this.totalPaid = value;
    }

    /**
     * Gets the value of the ingredientCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIngredientCost() {
        return ingredientCost;
    }

    /**
     * Sets the value of the ingredientCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIngredientCost(BigDecimal value) {
        this.ingredientCost = value;
    }

    /**
     * Gets the value of the dispensingFee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDispensingFee() {
        return dispensingFee;
    }

    /**
     * Sets the value of the dispensingFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDispensingFee(BigDecimal value) {
        this.dispensingFee = value;
    }

    /**
     * Gets the value of the averageWholesalePrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAverageWholesalePrice() {
        return averageWholesalePrice;
    }

    /**
     * Sets the value of the averageWholesalePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAverageWholesalePrice(BigDecimal value) {
        this.averageWholesalePrice = value;
    }

    /**
     * Gets the value of the payerPlanPeriodSourceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerPlanPeriodSourceIdentifier() {
        return payerPlanPeriodSourceIdentifier;
    }

    /**
     * Sets the value of the payerPlanPeriodSourceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerPlanPeriodSourceIdentifier(String value) {
        this.payerPlanPeriodSourceIdentifier = value;
    }

}
