/*
*   Copyright 2012-2013 The Regents of the University of Colorado
*
*   Licensed under the Apache License, Version 2.0 (the "License")
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.21 at 10:33:43 PM EDT 
//


package edu.ucdenver.rosita.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for drug_exposure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="drug_exposure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="drug_exposure_source_identifier" type="{}string_max50"/>
 *         &lt;element name="x_data_source_type" type="{}string_max20"/>
 *         &lt;element name="person_source_value" type="{}string_max50"/>
 *         &lt;element name="drug_source_value" type="{}string_max50"/>
 *         &lt;element name="drug_source_value_vocabulary" type="{}string_max50"/>
 *         &lt;element name="drug_exposure_start_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="drug_exposure_end_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="drug_type_source_value" type="{}string_max50"/>
 *         &lt;element name="stop_reason" type="{}string_max20"/>
 *         &lt;element name="refills" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="days_supply" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="x_drug_name" type="{}string_max255"/>
 *         &lt;element name="x_drug_strength" type="{}string_max50"/>
 *         &lt;element name="sig" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="provider_source_value" type="{}string_max50"/>
 *         &lt;element name="visit_occurrence_source_identifier" type="{}string_max50"/>
 *         &lt;element name="relevant_condition_source_value" type="{}string_max50"/>
 *         &lt;element name="drug_cost" type="{}drug_cost" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "drug_exposure", propOrder = {
    "drugExposureSourceIdentifier",
    "xDataSourceType",
    "personSourceValue",
    "drugSourceValue",
    "drugSourceValueVocabulary",
    "drugExposureStartDate",
    "drugExposureEndDate",
    "drugTypeSourceValue",
    "stopReason",
    "refills",
    "quantity",
    "daysSupply",
    "xDrugName",
    "xDrugStrength",
    "sig",
    "providerSourceValue",
    "xVisitOccurrenceSourceIdentifier",
    "relevantConditionSourceValue",
    "drugCost"
})
public class DrugExposure {

    @XmlElement(name = "drug_exposure_source_identifier", required = true)
    protected String drugExposureSourceIdentifier;
    @XmlElement(name = "x_data_source_type", required = true)
    protected String xDataSourceType;
    @XmlElement(name = "person_source_value", required = true)
    protected String personSourceValue;
    @XmlElement(name = "drug_source_value", required = true, nillable = true)
    protected String drugSourceValue;
    @XmlElement(name = "drug_source_value_vocabulary", required = true, nillable = true)
    protected String drugSourceValueVocabulary;
    @XmlElement(name = "drug_exposure_start_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar drugExposureStartDate;
    @XmlElement(name = "drug_exposure_end_date", required = true, nillable = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar drugExposureEndDate;
    @XmlElement(name = "drug_type_source_value", required = true)
    protected String drugTypeSourceValue;
    @XmlElement(name = "stop_reason", required = true, nillable = true)
    protected String stopReason;
    @XmlElement(required = true, nillable = true)
    protected BigInteger refills;
    @XmlElement(required = true, nillable = true)
    protected BigInteger quantity;
    @XmlElement(name = "days_supply", required = true, nillable = true)
    protected BigInteger daysSupply;
    @XmlElement(name = "x_drug_name", required = true)
    protected String xDrugName;
    @XmlElement(name = "x_drug_strength", required = true, nillable = true)
    protected String xDrugStrength;
    @XmlElement(required = true, nillable = true)
    protected String sig;
    @XmlElement(name = "provider_source_value", required = true, nillable = true)
    protected String providerSourceValue;
    @XmlElement(name = "x_visit_occurrence_source_identifier", required = true, nillable = true)
    protected String xVisitOccurrenceSourceIdentifier;
    @XmlElement(name = "relevant_condition_source_value", required = true, nillable = true)
    protected String relevantConditionSourceValue;
    @XmlElement(name = "drug_cost")
    protected List<DrugCost> drugCost;

    /**
     * Gets the value of the drugExposureSourceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugExposureSourceIdentifier() {
        return drugExposureSourceIdentifier;
    }

    /**
     * Sets the value of the drugExposureSourceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugExposureSourceIdentifier(String value) {
        this.drugExposureSourceIdentifier = value;
    }

    /**
     * Gets the value of the xDataSourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXDataSourceType() {
        return xDataSourceType;
    }

    /**
     * Sets the value of the xDataSourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXDataSourceType(String value) {
        this.xDataSourceType = value;
    }

    /**
     * Gets the value of the personSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonSourceValue() {
        return personSourceValue;
    }

    /**
     * Sets the value of the personSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonSourceValue(String value) {
        this.personSourceValue = value;
    }

    /**
     * Gets the value of the drugSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugSourceValue() {
        return drugSourceValue;
    }

    /**
     * Sets the value of the drugSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugSourceValue(String value) {
        this.drugSourceValue = value;
    }

    /**
     * Gets the value of the drugSourceValueVocabulary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugSourceValueVocabulary() {
        return drugSourceValueVocabulary;
    }

    /**
     * Sets the value of the drugSourceValueVocabulary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugSourceValueVocabulary(String value) {
        this.drugSourceValueVocabulary = value;
    }

    /**
     * Gets the value of the drugExposureStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDrugExposureStartDate() {
        return drugExposureStartDate;
    }

    /**
     * Sets the value of the drugExposureStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDrugExposureStartDate(XMLGregorianCalendar value) {
        this.drugExposureStartDate = value;
    }

    /**
     * Gets the value of the drugExposureEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDrugExposureEndDate() {
        return drugExposureEndDate;
    }

    /**
     * Sets the value of the drugExposureEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDrugExposureEndDate(XMLGregorianCalendar value) {
        this.drugExposureEndDate = value;
    }

    /**
     * Gets the value of the drugTypeSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugTypeSourceValue() {
        return drugTypeSourceValue;
    }

    /**
     * Sets the value of the drugTypeSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugTypeSourceValue(String value) {
        this.drugTypeSourceValue = value;
    }

    /**
     * Gets the value of the stopReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopReason() {
        return stopReason;
    }

    /**
     * Sets the value of the stopReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopReason(String value) {
        this.stopReason = value;
    }

    /**
     * Gets the value of the refills property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRefills() {
        return refills;
    }

    /**
     * Sets the value of the refills property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRefills(BigInteger value) {
        this.refills = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQuantity(BigInteger value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the daysSupply property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDaysSupply() {
        return daysSupply;
    }

    /**
     * Sets the value of the daysSupply property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDaysSupply(BigInteger value) {
        this.daysSupply = value;
    }

    /**
     * Gets the value of the xDrugName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXDrugName() {
        return xDrugName;
    }

    /**
     * Sets the value of the xDrugName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXDrugName(String value) {
        this.xDrugName = value;
    }

    /**
     * Gets the value of the xDrugStrength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXDrugStrength() {
        return xDrugStrength;
    }

    /**
     * Sets the value of the xDrugStrength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXDrugStrength(String value) {
        this.xDrugStrength = value;
    }

    /**
     * Gets the value of the sig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSig() {
        return sig;
    }

    /**
     * Sets the value of the sig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSig(String value) {
        this.sig = value;
    }

    /**
     * Gets the value of the providerSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderSourceValue() {
        return providerSourceValue;
    }

    /**
     * Sets the value of the providerSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderSourceValue(String value) {
        this.providerSourceValue = value;
    }

    /**
     * Gets the value of the visitOccurrenceSourceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getxVisitOccurrenceSourceIdentifier() {
        return xVisitOccurrenceSourceIdentifier;
    }

    /**
     * Sets the value of the visitOccurrenceSourceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setxVisitOccurrenceSourceIdentifier(String value) {
        this.xVisitOccurrenceSourceIdentifier = value;
    }

    /**
     * Gets the value of the relevantConditionSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelevantConditionSourceValue() {
        return relevantConditionSourceValue;
    }

    /**
     * Sets the value of the relevantConditionSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelevantConditionSourceValue(String value) {
        this.relevantConditionSourceValue = value;
    }

    /**
     * Gets the value of the drugCost property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the drugCost property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDrugCost().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DrugCost }
     * 
     * 
     */
    public List<DrugCost> getDrugCost() {
        if (drugCost == null) {
            drugCost = new ArrayList<DrugCost>();
        }
        return this.drugCost;
    }

}
