/*
*   Copyright 2012-2013 The Regents of the University of Colorado
*
*   Licensed under the Apache License, Version 2.0 (the "License")
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.21 at 10:33:43 PM EDT 
//


package edu.ucdenver.rosita.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.ucdenver.rosita.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Cohort_QNAME = new QName("", "cohort");
    private final static QName _CareSite_QNAME = new QName("", "care_site");
    private final static QName _Observation_QNAME = new QName("", "observation");
    private final static QName _Death_QNAME = new QName("", "death");
    private final static QName _ProcedureCost_QNAME = new QName("", "procedure_cost");
    private final static QName _Provider_QNAME = new QName("", "provider");
    private final static QName _DrugExposure_QNAME = new QName("", "drug_exposure");
    private final static QName _PayerPlanPeriod_QNAME = new QName("", "payer_plan_period");
    private final static QName _Organization_QNAME = new QName("", "organization");
    private final static QName _ConditionOccurrence_QNAME = new QName("", "condition_occurrence");
    private final static QName _DrugCost_QNAME = new QName("", "drug_cost");
    private final static QName _ProcedureOccurrence_QNAME = new QName("", "procedure_occurrence");
    private final static QName _XDemographic_QNAME = new QName("", "x_demographic");
    private final static QName _VisitOccurrence_QNAME = new QName("", "visit_occurrence");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.ucdenver.rosita.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VisitOccurrence }
     * 
     */
    public VisitOccurrence createVisitOccurrence() {
        return new VisitOccurrence();
    }

    /**
     * Create an instance of {@link CareSite }
     * 
     */
    public CareSite createCareSite() {
        return new CareSite();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link ProcedureCost }
     * 
     */
    public ProcedureCost createProcedureCost() {
        return new ProcedureCost();
    }

    /**
     * Create an instance of {@link Observation }
     * 
     */
    public Observation createObservation() {
        return new Observation();
    }

    /**
     * Create an instance of {@link XDemographic }
     * 
     */
    public XDemographic createXDemographic() {
        return new XDemographic();
    }

    /**
     * Create an instance of {@link PayerPlanPeriod }
     * 
     */
    public PayerPlanPeriod createPayerPlanPeriod() {
        return new PayerPlanPeriod();
    }

    /**
     * Create an instance of {@link ProcedureOccurrence }
     * 
     */
    public ProcedureOccurrence createProcedureOccurrence() {
        return new ProcedureOccurrence();
    }

    /**
     * Create an instance of {@link Cohort }
     * 
     */
    public Cohort createCohort() {
        return new Cohort();
    }

    /**
     * Create an instance of {@link Provider }
     * 
     */
    public Provider createProvider() {
        return new Provider();
    }

    /**
     * Create an instance of {@link Death }
     * 
     */
    public Death createDeath() {
        return new Death();
    }

    /**
     * Create an instance of {@link DrugExposure }
     * 
     */
    public DrugExposure createDrugExposure() {
        return new DrugExposure();
    }

    /**
     * Create an instance of {@link DrugCost }
     * 
     */
    public DrugCost createDrugCost() {
        return new DrugCost();
    }

    /**
     * Create an instance of {@link ConditionOccurrence }
     * 
     */
    public ConditionOccurrence createConditionOccurrence() {
        return new ConditionOccurrence();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cohort }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cohort")
    public JAXBElement<Cohort> createCohort(Cohort value) {
        return new JAXBElement<Cohort>(_Cohort_QNAME, Cohort.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CareSite }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "care_site")
    public JAXBElement<CareSite> createCareSite(CareSite value) {
        return new JAXBElement<CareSite>(_CareSite_QNAME, CareSite.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Observation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "observation")
    public JAXBElement<Observation> createObservation(Observation value) {
        return new JAXBElement<Observation>(_Observation_QNAME, Observation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Death }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "death")
    public JAXBElement<Death> createDeath(Death value) {
        return new JAXBElement<Death>(_Death_QNAME, Death.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcedureCost }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "procedure_cost")
    public JAXBElement<ProcedureCost> createProcedureCost(ProcedureCost value) {
        return new JAXBElement<ProcedureCost>(_ProcedureCost_QNAME, ProcedureCost.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Provider }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "provider")
    public JAXBElement<Provider> createProvider(Provider value) {
        return new JAXBElement<Provider>(_Provider_QNAME, Provider.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DrugExposure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "drug_exposure")
    public JAXBElement<DrugExposure> createDrugExposure(DrugExposure value) {
        return new JAXBElement<DrugExposure>(_DrugExposure_QNAME, DrugExposure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PayerPlanPeriod }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "payer_plan_period")
    public JAXBElement<PayerPlanPeriod> createPayerPlanPeriod(PayerPlanPeriod value) {
        return new JAXBElement<PayerPlanPeriod>(_PayerPlanPeriod_QNAME, PayerPlanPeriod.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Organization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "organization")
    public JAXBElement<Organization> createOrganization(Organization value) {
        return new JAXBElement<Organization>(_Organization_QNAME, Organization.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConditionOccurrence }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "condition_occurrence")
    public JAXBElement<ConditionOccurrence> createConditionOccurrence(ConditionOccurrence value) {
        return new JAXBElement<ConditionOccurrence>(_ConditionOccurrence_QNAME, ConditionOccurrence.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DrugCost }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "drug_cost")
    public JAXBElement<DrugCost> createDrugCost(DrugCost value) {
        return new JAXBElement<DrugCost>(_DrugCost_QNAME, DrugCost.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcedureOccurrence }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "procedure_occurrence")
    public JAXBElement<ProcedureOccurrence> createProcedureOccurrence(ProcedureOccurrence value) {
        return new JAXBElement<ProcedureOccurrence>(_ProcedureOccurrence_QNAME, ProcedureOccurrence.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XDemographic }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "x_demographic")
    public JAXBElement<XDemographic> createXDemographic(XDemographic value) {
        return new JAXBElement<XDemographic>(_XDemographic_QNAME, XDemographic.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VisitOccurrence }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "visit_occurrence")
    public JAXBElement<VisitOccurrence> createVisitOccurrence(VisitOccurrence value) {
        return new JAXBElement<VisitOccurrence>(_VisitOccurrence_QNAME, VisitOccurrence.class, null, value);
    }

}
