/*
*   Copyright 2012-2013 The Regents of the University of Colorado
*
*   Licensed under the Apache License, Version 2.0 (the "License")
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.21 at 10:33:43 PM EDT 
//


package edu.ucdenver.rosita.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for observation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="observation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="observation_source_identifier" type="{}string_max50"/>
 *         &lt;element name="x_data_source_type" type="{}string_max20"/>
 *         &lt;element name="person_source_value" type="{}string_max50"/>
 *         &lt;element name="observation_source_value" type="{}string_max50"/>
 *         &lt;element name="observation_source_value_vocabulary" type="{}string_max50"/>
 *         &lt;element name="observation_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="observation_time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="value_as_number" type="{}decimal_precision14_scale3"/>
 *         &lt;element name="value_as_string" type="{}string_max60"/>
 *         &lt;element name="unit_source_value" type="{}string_max50"/>
 *         &lt;element name="range_low" type="{}decimal_precision14_scale3"/>
 *         &lt;element name="range_high" type="{}decimal_precision14_scale3"/>
 *         &lt;element name="observation_type_source_value" type="{}string_max50"/>
 *         &lt;element name="associated_provider_source_value" type="{}string_max50"/>
 *         &lt;element name="visit_occurrence_source_value" type="{}string_max50"/>
 *         &lt;element name="relevant_condition_source_value" type="{}string_max50"/>
 *         &lt;element name="x_obs_comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "observation", propOrder = {
    "observationSourceIdentifier",
    "xDataSourceType",
    "personSourceValue",
    "observationSourceValue",
    "observationSourceValueVocabulary",
    "observationDate",
    "observationTime",
    "valueAsNumber",
    "valueAsString",
    "unitSourceValue",
    "rangeLow",
    "rangeHigh",
    "observationTypeSourceValue",
    "associatedProviderSourceValue",
    "xVisitOccurrenceSourceIdentifier",
    "relevantConditionSourceValue",
    "xObsComment"
})
public class Observation {

    @XmlElement(name = "observation_source_identifier", required = true)
    protected String observationSourceIdentifier;
    @XmlElement(name = "x_data_source_type", required = true)
    protected String xDataSourceType;
    @XmlElement(name = "person_source_value", required = true)
    protected String personSourceValue;
    @XmlElement(name = "observation_source_value", required = true)
    protected String observationSourceValue;
    @XmlElement(name = "observation_source_value_vocabulary", required = true)
    protected String observationSourceValueVocabulary;
    @XmlElement(name = "observation_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar observationDate;
    @XmlElement(name = "observation_time", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar observationTime;
    @XmlElement(name = "value_as_number", required = true, nillable = true)
    protected BigDecimal valueAsNumber;
    @XmlElement(name = "value_as_string", required = true, nillable = true)
    protected String valueAsString;
    @XmlElement(name = "unit_source_value", required = true, nillable = true)
    protected String unitSourceValue;
    @XmlElement(name = "range_low", required = true, nillable = true)
    protected BigDecimal rangeLow;
    @XmlElement(name = "range_high", required = true, nillable = true)
    protected BigDecimal rangeHigh;
    @XmlElement(name = "observation_type_source_value", required = true)
    protected String observationTypeSourceValue;
    @XmlElement(name = "associated_provider_source_value", required = true, nillable = true)
    protected String associatedProviderSourceValue;
    @XmlElement(name = "x_visit_occurrence_source_identifier", required = true, nillable = true)
    protected String xVisitOccurrenceSourceIdentifier;
    @XmlElement(name = "relevant_condition_source_value", required = true, nillable = true)
    protected String relevantConditionSourceValue;
    @XmlElement(name = "x_obs_comment", required = true, nillable = true)
    protected String xObsComment;

    /**
     * Gets the value of the observationSourceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservationSourceIdentifier() {
        return observationSourceIdentifier;
    }

    /**
     * Sets the value of the observationSourceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservationSourceIdentifier(String value) {
        this.observationSourceIdentifier = value;
    }

    /**
     * Gets the value of the xDataSourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXDataSourceType() {
        return xDataSourceType;
    }

    /**
     * Sets the value of the xDataSourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXDataSourceType(String value) {
        this.xDataSourceType = value;
    }

    /**
     * Gets the value of the personSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonSourceValue() {
        return personSourceValue;
    }

    /**
     * Sets the value of the personSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonSourceValue(String value) {
        this.personSourceValue = value;
    }

    /**
     * Gets the value of the observationSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservationSourceValue() {
        return observationSourceValue;
    }

    /**
     * Sets the value of the observationSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservationSourceValue(String value) {
        this.observationSourceValue = value;
    }

    /**
     * Gets the value of the observationSourceValueVocabulary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservationSourceValueVocabulary() {
        return observationSourceValueVocabulary;
    }

    /**
     * Sets the value of the observationSourceValueVocabulary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservationSourceValueVocabulary(String value) {
        this.observationSourceValueVocabulary = value;
    }

    /**
     * Gets the value of the observationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getObservationDate() {
        return observationDate;
    }

    /**
     * Sets the value of the observationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setObservationDate(XMLGregorianCalendar value) {
        this.observationDate = value;
    }

    /**
     * Gets the value of the observationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getObservationTime() {
        return observationTime;
    }

    /**
     * Sets the value of the observationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setObservationTime(XMLGregorianCalendar value) {
        this.observationTime = value;
    }

    /**
     * Gets the value of the valueAsNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValueAsNumber() {
        return valueAsNumber;
    }

    /**
     * Sets the value of the valueAsNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValueAsNumber(BigDecimal value) {
        this.valueAsNumber = value;
    }

    /**
     * Gets the value of the valueAsString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueAsString() {
        return valueAsString;
    }

    /**
     * Sets the value of the valueAsString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueAsString(String value) {
        this.valueAsString = value;
    }

    /**
     * Gets the value of the unitSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitSourceValue() {
        return unitSourceValue;
    }

    /**
     * Sets the value of the unitSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitSourceValue(String value) {
        this.unitSourceValue = value;
    }

    /**
     * Gets the value of the rangeLow property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRangeLow() {
        return rangeLow;
    }

    /**
     * Sets the value of the rangeLow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRangeLow(BigDecimal value) {
        this.rangeLow = value;
    }

    /**
     * Gets the value of the rangeHigh property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRangeHigh() {
        return rangeHigh;
    }

    /**
     * Sets the value of the rangeHigh property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRangeHigh(BigDecimal value) {
        this.rangeHigh = value;
    }

    /**
     * Gets the value of the observationTypeSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservationTypeSourceValue() {
        return observationTypeSourceValue;
    }

    /**
     * Sets the value of the observationTypeSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservationTypeSourceValue(String value) {
        this.observationTypeSourceValue = value;
    }

    /**
     * Gets the value of the associatedProviderSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociatedProviderSourceValue() {
        return associatedProviderSourceValue;
    }

    /**
     * Sets the value of the associatedProviderSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociatedProviderSourceValue(String value) {
        this.associatedProviderSourceValue = value;
    }

    /**
     * Gets the value of the visitOccurrenceSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getxVisitOccurrenceSourceIdentifier() {
        return xVisitOccurrenceSourceIdentifier;
    }

    /**
     * Sets the value of the visitOccurrenceSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setxVisitOccurrenceSourceIdentifier(String value) {
        this.xVisitOccurrenceSourceIdentifier = value;
    }

    /**
     * Gets the value of the relevantConditionSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelevantConditionSourceValue() {
        return relevantConditionSourceValue;
    }

    /**
     * Sets the value of the relevantConditionSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelevantConditionSourceValue(String value) {
        this.relevantConditionSourceValue = value;
    }

    /**
     * Gets the value of the xObsComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXObsComment() {
        return xObsComment;
    }

    /**
     * Sets the value of the xObsComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXObsComment(String value) {
        this.xObsComment = value;
    }

}
