/*
*   Copyright 2012-2013 The Regents of the University of Colorado
*
*   Licensed under the Apache License, Version 2.0 (the "License")
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.21 at 10:33:43 PM EDT 
//


package edu.ucdenver.rosita.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for organization complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="organization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="organization_source_value" type="{}string_max50"/>
 *         &lt;element name="x_data_source_type" type="{}string_max20"/>
 *         &lt;element name="place_of_service_source_value" type="{}string_max50"/>
 *         &lt;element name="organization_address_1" type="{}string_max50"/>
 *         &lt;element name="organization_address_2" type="{}string_max50"/>
 *         &lt;element name="organization_city" type="{}string_max50"/>
 *         &lt;element name="organization_state" type="{}string_max2"/>
 *         &lt;element name="organization_zip" type="{}string_max9"/>
 *         &lt;element name="organization_county" type="{}string_max20"/>
 *         &lt;element name="care_site" type="{}care_site" maxOccurs="unbounded"/>
 *         &lt;element name="x_demographic" type="{}x_demographic" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "organization", propOrder = {
    "organizationSourceValue",
    "xDataSourceType",
    "placeOfServiceSourceValue",
    "organizationAddress1",
    "organizationAddress2",
    "organizationCity",
    "organizationState",
    "organizationZip",
    "organizationCounty",
    "careSite",
    "xDemographic"
})
public class Organization {

    @XmlElement(name = "organization_source_value", required = true)
    protected String organizationSourceValue;
    @XmlElement(name = "x_data_source_type", required = true)
    protected String xDataSourceType;
    @XmlElement(name = "place_of_service_source_value", required = true)
    protected String placeOfServiceSourceValue;
    @XmlElement(name = "organization_address_1", required = true, nillable = true)
    protected String organizationAddress1;
    @XmlElement(name = "organization_address_2", required = true, nillable = true)
    protected String organizationAddress2;
    @XmlElement(name = "organization_city", required = true, nillable = true)
    protected String organizationCity;
    @XmlElement(name = "organization_state", required = true, nillable = true)
    protected String organizationState;
    @XmlElement(name = "organization_zip", required = true, nillable = true)
    protected String organizationZip;
    @XmlElement(name = "organization_county", required = true, nillable = true)
    protected String organizationCounty;
    @XmlElement(name = "care_site", required = true)
    protected List<CareSite> careSite;
    @XmlElement(name = "x_demographic", required = true)
    protected List<XDemographic> xDemographic;

    /**
     * Gets the value of the organizationSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationSourceValue() {
        return organizationSourceValue;
    }

    /**
     * Sets the value of the organizationSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationSourceValue(String value) {
        this.organizationSourceValue = value;
    }

    /**
     * Gets the value of the xDataSourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXDataSourceType() {
        return xDataSourceType;
    }

    /**
     * Sets the value of the xDataSourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXDataSourceType(String value) {
        this.xDataSourceType = value;
    }

    /**
     * Gets the value of the placeOfServiceSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceOfServiceSourceValue() {
        return placeOfServiceSourceValue;
    }

    /**
     * Sets the value of the placeOfServiceSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceOfServiceSourceValue(String value) {
        this.placeOfServiceSourceValue = value;
    }

    /**
     * Gets the value of the organizationAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationAddress1() {
        return organizationAddress1;
    }

    /**
     * Sets the value of the organizationAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationAddress1(String value) {
        this.organizationAddress1 = value;
    }

    /**
     * Gets the value of the organizationAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationAddress2() {
        return organizationAddress2;
    }

    /**
     * Sets the value of the organizationAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationAddress2(String value) {
        this.organizationAddress2 = value;
    }

    /**
     * Gets the value of the organizationCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationCity() {
        return organizationCity;
    }

    /**
     * Sets the value of the organizationCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationCity(String value) {
        this.organizationCity = value;
    }

    /**
     * Gets the value of the organizationState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationState() {
        return organizationState;
    }

    /**
     * Sets the value of the organizationState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationState(String value) {
        this.organizationState = value;
    }

    /**
     * Gets the value of the organizationZip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationZip() {
        return organizationZip;
    }

    /**
     * Sets the value of the organizationZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationZip(String value) {
        this.organizationZip = value;
    }

    /**
     * Gets the value of the organizationCounty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationCounty() {
        return organizationCounty;
    }

    /**
     * Sets the value of the organizationCounty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationCounty(String value) {
        this.organizationCounty = value;
    }

    /**
     * Gets the value of the careSite property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the careSite property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCareSite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CareSite }
     * 
     * 
     */
    public List<CareSite> getCareSite() {
        if (careSite == null) {
            careSite = new ArrayList<CareSite>();
        }
        return this.careSite;
    }

    /**
     * Gets the value of the xDemographic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xDemographic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXDemographic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XDemographic }
     * 
     * 
     */
    public List<XDemographic> getXDemographic() {
        if (xDemographic == null) {
            xDemographic = new ArrayList<XDemographic>();
        }
        return this.xDemographic;
    }

}
