/*
*   Copyright 2012-2013 The Regents of the University of Colorado
*
*   Licensed under the Apache License, Version 2.0 (the "License")
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.21 at 10:33:43 PM EDT 
//


package edu.ucdenver.rosita.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for payer_plan_period complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="payer_plan_period">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="payer_plan_period_source_identifier" type="{}string_max50"/>
 *         &lt;element name="person_source_value" type="{}string_max50"/>
 *         &lt;element name="payer_plan_period_start_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="payer_plan_period_end_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="payer_source_value" type="{}string_max50"/>
 *         &lt;element name="plan_source_value" type="{}string_max50"/>
 *         &lt;element name="family_source_value" type="{}string_max50"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "payer_plan_period", propOrder = {
    "payerPlanPeriodSourceIdentifier",
    "personSourceValue",
    "payerPlanPeriodStartDate",
    "payerPlanPeriodEndDate",
    "payerSourceValue",
    "planSourceValue",
    "familySourceValue"
})
public class PayerPlanPeriod {

    @XmlElement(name = "payer_plan_period_source_identifier", required = true)
    protected String payerPlanPeriodSourceIdentifier;
    @XmlElement(name = "person_source_value", required = true)
    protected String personSourceValue;
    @XmlElement(name = "payer_plan_period_start_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar payerPlanPeriodStartDate;
    @XmlElement(name = "payer_plan_period_end_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar payerPlanPeriodEndDate;
    @XmlElement(name = "payer_source_value", required = true, nillable = true)
    protected String payerSourceValue;
    @XmlElement(name = "plan_source_value", required = true, nillable = true)
    protected String planSourceValue;
    @XmlElement(name = "family_source_value", required = true, nillable = true)
    protected String familySourceValue;

    /**
     * Gets the value of the payerPlanPeriodSourceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerPlanPeriodSourceIdentifier() {
        return payerPlanPeriodSourceIdentifier;
    }

    /**
     * Sets the value of the payerPlanPeriodSourceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerPlanPeriodSourceIdentifier(String value) {
        this.payerPlanPeriodSourceIdentifier = value;
    }

    /**
     * Gets the value of the personSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonSourceValue() {
        return personSourceValue;
    }

    /**
     * Sets the value of the personSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonSourceValue(String value) {
        this.personSourceValue = value;
    }

    /**
     * Gets the value of the payerPlanPeriodStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPayerPlanPeriodStartDate() {
        return payerPlanPeriodStartDate;
    }

    /**
     * Sets the value of the payerPlanPeriodStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPayerPlanPeriodStartDate(XMLGregorianCalendar value) {
        this.payerPlanPeriodStartDate = value;
    }

    /**
     * Gets the value of the payerPlanPeriodEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPayerPlanPeriodEndDate() {
        return payerPlanPeriodEndDate;
    }

    /**
     * Sets the value of the payerPlanPeriodEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPayerPlanPeriodEndDate(XMLGregorianCalendar value) {
        this.payerPlanPeriodEndDate = value;
    }

    /**
     * Gets the value of the payerSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerSourceValue() {
        return payerSourceValue;
    }

    /**
     * Sets the value of the payerSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerSourceValue(String value) {
        this.payerSourceValue = value;
    }

    /**
     * Gets the value of the planSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanSourceValue() {
        return planSourceValue;
    }

    /**
     * Sets the value of the planSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanSourceValue(String value) {
        this.planSourceValue = value;
    }

    /**
     * Gets the value of the familySourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilySourceValue() {
        return familySourceValue;
    }

    /**
     * Sets the value of the familySourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilySourceValue(String value) {
        this.familySourceValue = value;
    }

}
