/*
*   Copyright 2012-2013 The Regents of the University of Colorado
*
*   Licensed under the Apache License, Version 2.0 (the "License")
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.21 at 10:33:43 PM EDT 
//


package edu.ucdenver.rosita.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for procedure_occurrence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="procedure_occurrence">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="procedure_occurrence_source_identifier" type="{}string_max50"/>
 *         &lt;element name="x_data_source_type" type="{}string_max20"/>
 *         &lt;element name="person_source_value" type="{}string_max50"/>
 *         &lt;element name="procedure_source_value" type="{}string_max50"/>
 *         &lt;element name="procedure_type_source_vocabulary" type="{}string_max50"/>
 *         &lt;element name="procedure_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="procedure_type_source_value" type="{}string_max50"/>
 *         &lt;element name="provider_record_source_value" type="{}string_max50"/>
 *         &lt;element name="visit_occurrence_source_value" type="{}string_max50"/>
 *         &lt;element name="relevant_condition_source_value" type="{}string_max50"/>
 *         &lt;element name="procedure_cost" type="{}procedure_cost" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "procedure_occurrence", propOrder = {
    "procedureOccurrenceSourceIdentifier",
    "xDataSourceType",
    "personSourceValue",
    "procedureSourceValue",
    "procedureSourceValueVocabulary",
    "procedureDate",
    "procedureTypeSourceValue",
    "providerRecordSourceValue",
    "xVisitOccurrenceSourceIdentifier",
    "relevantConditionSourceValue",
    "procedureCost"
})
public class ProcedureOccurrence {

    @XmlElement(name = "procedure_occurrence_source_identifier", required = true)
    protected String procedureOccurrenceSourceIdentifier;
    @XmlElement(name = "x_data_source_type", required = true)
    protected String xDataSourceType;
    @XmlElement(name = "person_source_value", required = true)
    protected String personSourceValue;
    @XmlElement(name = "procedure_source_value", required = true)
    protected String procedureSourceValue;
    @XmlElement(name = "procedure_source_value_vocabulary", required = true)
    protected String procedureSourceValueVocabulary;
    @XmlElement(name = "procedure_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar procedureDate;
    @XmlElement(name = "procedure_type_source_value", required = true, nillable = true)
    protected String procedureTypeSourceValue;
    @XmlElement(name = "provider_record_source_value", required = true, nillable = true)
    protected String providerRecordSourceValue;
    @XmlElement(name = "x_visit_occurrence_source_identifier", required = true, nillable = true)
    protected String xVisitOccurrenceSourceIdentifier;
    @XmlElement(name = "relevant_condition_source_value", required = true, nillable = true)
    protected String relevantConditionSourceValue;
    @XmlElement(name = "procedure_cost")
    protected List<ProcedureCost> procedureCost;

    /**
     * Gets the value of the procedureOccurrenceSourceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcedureOccurrenceSourceIdentifier() {
        return procedureOccurrenceSourceIdentifier;
    }

    /**
     * Sets the value of the procedureOccurrenceSourceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcedureOccurrenceSourceIdentifier(String value) {
        this.procedureOccurrenceSourceIdentifier = value;
    }

    /**
     * Gets the value of the xDataSourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXDataSourceType() {
        return xDataSourceType;
    }

    /**
     * Sets the value of the xDataSourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXDataSourceType(String value) {
        this.xDataSourceType = value;
    }

    /**
     * Gets the value of the personSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonSourceValue() {
        return personSourceValue;
    }

    /**
     * Sets the value of the personSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonSourceValue(String value) {
        this.personSourceValue = value;
    }

    /**
     * Gets the value of the procedureSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcedureSourceValue() {
        return procedureSourceValue;
    }

    /**
     * Sets the value of the procedureSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcedureSourceValue(String value) {
        this.procedureSourceValue = value;
    }

    /**
     * Gets the value of the procedureTypeSourceVocabulary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcedureSourceValueVocabulary() {
        return procedureSourceValueVocabulary;
    }

    /**
     * Sets the value of the procedureTypeSourceVocabulary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcedureSourceValueVocabulary(String value) {
        this.procedureSourceValueVocabulary = value;
    }

    /**
     * Gets the value of the procedureDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProcedureDate() {
        return procedureDate;
    }

    /**
     * Sets the value of the procedureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProcedureDate(XMLGregorianCalendar value) {
        this.procedureDate = value;
    }

    /**
     * Gets the value of the procedureTypeSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcedureTypeSourceValue() {
        return procedureTypeSourceValue;
    }

    /**
     * Sets the value of the procedureTypeSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcedureTypeSourceValue(String value) {
        this.procedureTypeSourceValue = value;
    }

    /**
     * Gets the value of the providerRecordSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderRecordSourceValue() {
        return providerRecordSourceValue;
    }

    /**
     * Sets the value of the providerRecordSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderRecordSourceValue(String value) {
        this.providerRecordSourceValue = value;
    }

    /**
     * Gets the value of the visitOccurrenceSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getxVisitOccurrenceSourceIdentifier() {
        return xVisitOccurrenceSourceIdentifier;
    }

    /**
     * Sets the value of the visitOccurrenceSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setxVisitOccurrenceSourceIdentifier(String value) {
        this.xVisitOccurrenceSourceIdentifier = value;
    }

    /**
     * Gets the value of the relevantConditionSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelevantConditionSourceValue() {
        return relevantConditionSourceValue;
    }

    /**
     * Sets the value of the relevantConditionSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelevantConditionSourceValue(String value) {
        this.relevantConditionSourceValue = value;
    }

    /**
     * Gets the value of the procedureCost property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the procedureCost property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcedureCost().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcedureCost }
     * 
     * 
     */
    public List<ProcedureCost> getProcedureCost() {
        if (procedureCost == null) {
            procedureCost = new ArrayList<ProcedureCost>();
        }
        return this.procedureCost;
    }

}
