/*
*   Copyright 2012-2013 The Regents of the University of Colorado
*
*   Licensed under the Apache License, Version 2.0 (the "License")
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.21 at 10:33:43 PM EDT 
//


package edu.ucdenver.rosita.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for visit_occurrence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="visit_occurrence">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="visit_occurrence_source_identifier" type="{}string_max50"/>
 *         &lt;element name="x_data_source_type" type="{}string_max20"/>
 *         &lt;element name="person_source_value" type="{}string_max50"/>
 *         &lt;element name="visit_start_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="visit_end_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="place_of_service_source_value" type="{}string_max50"/>
 *         &lt;element name="x_provider_source_value" type="{}string_max50"/>
 *         &lt;element name="care_site_source_value" type="{}string_max50"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "visit_occurrence", propOrder = {
    "xVisitOccurrenceSourceIdentifier",
    "xDataSourceType",
    "personSourceValue",
    "visitStartDate",
    "visitEndDate",
    "placeOfServiceSourceValue",
    "xProviderSourceValue",
    "careSiteSourceValue"
})
public class VisitOccurrence {

    @XmlElement(name = "x_visit_occurrence_source_identifier", required = true)
    protected String xVisitOccurrenceSourceIdentifier;
    @XmlElement(name = "x_data_source_type", required = true)
    protected String xDataSourceType;
    @XmlElement(name = "person_source_value", required = true)
    protected String personSourceValue;
    @XmlElement(name = "visit_start_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar visitStartDate;
    @XmlElement(name = "visit_end_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar visitEndDate;
    @XmlElement(name = "place_of_service_source_value", required = true, nillable = true)
    protected String placeOfServiceSourceValue;
    @XmlElement(name = "x_provider_source_value", required = true, nillable = true)
    protected String xProviderSourceValue;
    @XmlElement(name = "care_site_source_value", required = true, nillable = true)
    protected String careSiteSourceValue;

    /**
     * Gets the value of the visitOccurrenceSourceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getxVisitOccurrenceSourceIdentifier() {
        return xVisitOccurrenceSourceIdentifier;
    }

    /**
     * Sets the value of the visitOccurrenceSourceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setxVisitOccurrenceSourceIdentifier(String value) {
        this.xVisitOccurrenceSourceIdentifier = value;
    }

    /**
     * Gets the value of the xDataSourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXDataSourceType() {
        return xDataSourceType;
    }

    /**
     * Sets the value of the xDataSourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXDataSourceType(String value) {
        this.xDataSourceType = value;
    }

    /**
     * Gets the value of the personSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonSourceValue() {
        return personSourceValue;
    }

    /**
     * Sets the value of the personSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonSourceValue(String value) {
        this.personSourceValue = value;
    }

    /**
     * Gets the value of the visitStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVisitStartDate() {
        return visitStartDate;
    }

    /**
     * Sets the value of the visitStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVisitStartDate(XMLGregorianCalendar value) {
        this.visitStartDate = value;
    }

    /**
     * Gets the value of the visitEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVisitEndDate() {
        return visitEndDate;
    }

    /**
     * Sets the value of the visitEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVisitEndDate(XMLGregorianCalendar value) {
        this.visitEndDate = value;
    }

    /**
     * Gets the value of the placeOfServiceSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceOfServiceSourceValue() {
        return placeOfServiceSourceValue;
    }

    /**
     * Sets the value of the placeOfServiceSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceOfServiceSourceValue(String value) {
        this.placeOfServiceSourceValue = value;
    }

    /**
     * Gets the value of the xProviderSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXProviderSourceValue() {
        return xProviderSourceValue;
    }

    /**
     * Sets the value of the xProviderSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXProviderSourceValue(String value) {
        this.xProviderSourceValue = value;
    }

    /**
     * Gets the value of the careSiteSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCareSiteSourceValue() {
        return careSiteSourceValue;
    }

    /**
     * Sets the value of the careSiteSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCareSiteSourceValue(String value) {
        this.careSiteSourceValue = value;
    }

}
