/*
*   Copyright 2012-2013 The Regents of the University of Colorado
*
*   Licensed under the Apache License, Version 2.0 (the "License")
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.21 at 10:33:43 PM EDT 
//


package edu.ucdenver.rosita.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for x_demographic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="x_demographic">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="person_source_value" type="{}string_max50"/>
 *         &lt;element name="x_data_source_type" type="{}string_max50"/>
 *         &lt;element name="medicaid_id_number" type="{}string_max50"/>
 *         &lt;element name="ssn" type="{}string_max50"/>
 *         &lt;element name="last" type="{}string_max75"/>
 *         &lt;element name="middle" type="{}string_max75"/>
 *         &lt;element name="first" type="{}string_max75"/>
 *         &lt;element name="address_1" type="{}string_max50"/>
 *         &lt;element name="address_2" type="{}string_max50"/>
 *         &lt;element name="city" type="{}string_max50"/>
 *         &lt;element name="state" type="{}string_max2"/>
 *         &lt;element name="zip" type="{}string_max9"/>
 *         &lt;element name="county" type="{}string_max20"/>
 *         &lt;element name="year_of_birth" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="month_of_birth" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="day_of_birth" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="gender_source_value" type="{}string_max50"/>
 *         &lt;element name="race_source_value" type="{}string_max50"/>
 *         &lt;element name="ethnicity_source_value" type="{}string_max50"/>
 *         &lt;element name="provider_source_value" type="{}string_max50"/>
 *         &lt;element name="care_site_source_value" type="{}string_max50"/>
 *         &lt;element name="x_organization_source_value" type="{}string_max50"/>
 *         &lt;element name="visit_occurrence" type="{}visit_occurrence" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="observation" type="{}observation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="drug_exposure" type="{}drug_exposure" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="condition_occurrence" type="{}condition_occurrence" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="procedure_occurrence" type="{}procedure_occurrence" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cohort" type="{}cohort" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="death" type="{}death" minOccurs="0"/>
 *         &lt;element name="payer_plan_period" type="{}payer_plan_period" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "x_demographic", propOrder = {
    "personSourceValue",
    "xDataSourceType",
    "medicaidIdNumber",
    "ssn",
    "last",
    "middle",
    "first",
    "address1",
    "address2",
    "city",
    "state",
    "zip",
    "county",
    "yearOfBirth",
    "monthOfBirth",
    "dayOfBirth",
    "genderSourceValue",
    "raceSourceValue",
    "ethnicitySourceValue",
    "providerSourceValue",
    "careSiteSourceValue",
    "xOrganizationSourceValue",
    "visitOccurrence",
    "observation",
    "drugExposure",
    "conditionOccurrence",
    "procedureOccurrence",
    "cohort",
    "death",
    "payerPlanPeriod"
})
public class XDemographic {

    @XmlElement(name = "person_source_value", required = true)
    protected String personSourceValue;
    @XmlElement(name = "x_data_source_type", required = true)
    protected String xDataSourceType;
    @XmlElement(name = "medicaid_id_number", required = true, nillable = true)
    protected String medicaidIdNumber;
    @XmlElement(required = true, nillable = true)
    protected String ssn;
    @XmlElement(required = true, nillable = true)
    protected String last;
    @XmlElement(required = true, nillable = true)
    protected String middle;
    @XmlElement(required = true, nillable = true)
    protected String first;
    @XmlElement(name = "address_1", required = true, nillable = true)
    protected String address1;
    @XmlElement(name = "address_2", required = true, nillable = true)
    protected String address2;
    @XmlElement(required = true, nillable = true)
    protected String city;
    @XmlElement(required = true, nillable = true)
    protected String state;
    @XmlElement(required = true, nillable = true)
    protected String zip;
    @XmlElement(required = true, nillable = true)
    protected String county;
    @XmlElement(name = "year_of_birth", required = true)
    protected BigInteger yearOfBirth;
    @XmlElement(name = "month_of_birth", required = true, nillable = true)
    protected BigInteger monthOfBirth;
    @XmlElement(name = "day_of_birth", required = true, nillable = true)
    protected BigInteger dayOfBirth;
    @XmlElement(name = "gender_source_value", required = true, nillable = true)
    protected String genderSourceValue;
    @XmlElement(name = "race_source_value", required = true, nillable = true)
    protected String raceSourceValue;
    @XmlElement(name = "ethnicity_source_value", required = true, nillable = true)
    protected String ethnicitySourceValue;
    @XmlElement(name = "provider_source_value", required = true, nillable = true)
    protected String providerSourceValue;
    @XmlElement(name = "care_site_source_value", required = true, nillable = true)
    protected String careSiteSourceValue;
    @XmlElement(name = "x_organization_source_value", required = true)
    protected String xOrganizationSourceValue;
    @XmlElement(name = "visit_occurrence")
    protected List<VisitOccurrence> visitOccurrence;
    protected List<Observation> observation;
    @XmlElement(name = "drug_exposure")
    protected List<DrugExposure> drugExposure;
    @XmlElement(name = "condition_occurrence")
    protected List<ConditionOccurrence> conditionOccurrence;
    @XmlElement(name = "procedure_occurrence")
    protected List<ProcedureOccurrence> procedureOccurrence;
    protected List<Cohort> cohort;
    protected Death death;
    @XmlElement(name = "payer_plan_period")
    protected List<PayerPlanPeriod> payerPlanPeriod;

    /**
     * Gets the value of the personSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonSourceValue() {
        return personSourceValue;
    }

    /**
     * Sets the value of the personSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonSourceValue(String value) {
        this.personSourceValue = value;
    }

    /**
     * Gets the value of the xDataSourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXDataSourceType() {
        return xDataSourceType;
    }

    /**
     * Sets the value of the xDataSourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXDataSourceType(String value) {
        this.xDataSourceType = value;
    }

    /**
     * Gets the value of the medicaidIdNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicaidIdNumber() {
        return medicaidIdNumber;
    }

    /**
     * Sets the value of the medicaidIdNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicaidIdNumber(String value) {
        this.medicaidIdNumber = value;
    }

    /**
     * Gets the value of the ssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsn() {
        return ssn;
    }

    /**
     * Sets the value of the ssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsn(String value) {
        this.ssn = value;
    }

    /**
     * Gets the value of the last property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLast() {
        return last;
    }

    /**
     * Sets the value of the last property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLast(String value) {
        this.last = value;
    }

    /**
     * Gets the value of the middle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddle() {
        return middle;
    }

    /**
     * Sets the value of the middle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddle(String value) {
        this.middle = value;
    }

    /**
     * Gets the value of the first property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirst() {
        return first;
    }

    /**
     * Sets the value of the first property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirst(String value) {
        this.first = value;
    }

    /**
     * Gets the value of the address1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * Sets the value of the address1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress1(String value) {
        this.address1 = value;
    }

    /**
     * Gets the value of the address2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * Sets the value of the address2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress2(String value) {
        this.address2 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the zip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZip() {
        return zip;
    }

    /**
     * Sets the value of the zip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZip(String value) {
        this.zip = value;
    }

    /**
     * Gets the value of the county property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCounty() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCounty(String value) {
        this.county = value;
    }

    /**
     * Gets the value of the yearOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getYearOfBirth() {
        return yearOfBirth;
    }

    /**
     * Sets the value of the yearOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setYearOfBirth(BigInteger value) {
        this.yearOfBirth = value;
    }

    /**
     * Gets the value of the monthOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMonthOfBirth() {
        return monthOfBirth;
    }

    /**
     * Sets the value of the monthOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMonthOfBirth(BigInteger value) {
        this.monthOfBirth = value;
    }

    /**
     * Gets the value of the dayOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDayOfBirth() {
        return dayOfBirth;
    }

    /**
     * Sets the value of the dayOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDayOfBirth(BigInteger value) {
        this.dayOfBirth = value;
    }

    /**
     * Gets the value of the genderSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenderSourceValue() {
        return genderSourceValue;
    }

    /**
     * Sets the value of the genderSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenderSourceValue(String value) {
        this.genderSourceValue = value;
    }

    /**
     * Gets the value of the raceSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRaceSourceValue() {
        return raceSourceValue;
    }

    /**
     * Sets the value of the raceSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRaceSourceValue(String value) {
        this.raceSourceValue = value;
    }

    /**
     * Gets the value of the ethnicitySourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEthnicitySourceValue() {
        return ethnicitySourceValue;
    }

    /**
     * Sets the value of the ethnicitySourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEthnicitySourceValue(String value) {
        this.ethnicitySourceValue = value;
    }

    /**
     * Gets the value of the providerSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderSourceValue() {
        return providerSourceValue;
    }

    /**
     * Sets the value of the providerSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderSourceValue(String value) {
        this.providerSourceValue = value;
    }

    /**
     * Gets the value of the careSiteSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCareSiteSourceValue() {
        return careSiteSourceValue;
    }

    /**
     * Sets the value of the careSiteSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCareSiteSourceValue(String value) {
        this.careSiteSourceValue = value;
    }

    /**
     * Gets the value of the xOrganizationSourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXOrganizationSourceValue() {
        return xOrganizationSourceValue;
    }

    /**
     * Sets the value of the xOrganizationSourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXOrganizationSourceValue(String value) {
        this.xOrganizationSourceValue = value;
    }

    /**
     * Gets the value of the visitOccurrence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the visitOccurrence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVisitOccurrence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VisitOccurrence }
     * 
     * 
     */
    public List<VisitOccurrence> getVisitOccurrence() {
        if (visitOccurrence == null) {
            visitOccurrence = new ArrayList<VisitOccurrence>();
        }
        return this.visitOccurrence;
    }

    /**
     * Gets the value of the observation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the observation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObservation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Observation }
     * 
     * 
     */
    public List<Observation> getObservation() {
        if (observation == null) {
            observation = new ArrayList<Observation>();
        }
        return this.observation;
    }

    /**
     * Gets the value of the drugExposure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the drugExposure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDrugExposure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DrugExposure }
     * 
     * 
     */
    public List<DrugExposure> getDrugExposure() {
        if (drugExposure == null) {
            drugExposure = new ArrayList<DrugExposure>();
        }
        return this.drugExposure;
    }

    /**
     * Gets the value of the conditionOccurrence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conditionOccurrence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConditionOccurrence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConditionOccurrence }
     * 
     * 
     */
    public List<ConditionOccurrence> getConditionOccurrence() {
        if (conditionOccurrence == null) {
            conditionOccurrence = new ArrayList<ConditionOccurrence>();
        }
        return this.conditionOccurrence;
    }

    /**
     * Gets the value of the procedureOccurrence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the procedureOccurrence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcedureOccurrence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcedureOccurrence }
     * 
     * 
     */
    public List<ProcedureOccurrence> getProcedureOccurrence() {
        if (procedureOccurrence == null) {
            procedureOccurrence = new ArrayList<ProcedureOccurrence>();
        }
        return this.procedureOccurrence;
    }

    /**
     * Gets the value of the cohort property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cohort property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCohort().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cohort }
     * 
     * 
     */
    public List<Cohort> getCohort() {
        if (cohort == null) {
            cohort = new ArrayList<Cohort>();
        }
        return this.cohort;
    }

    /**
     * Gets the value of the death property.
     * 
     * @return
     *     possible object is
     *     {@link Death }
     *     
     */
    public Death getDeath() {
        return death;
    }

    /**
     * Sets the value of the death property.
     * 
     * @param value
     *     allowed object is
     *     {@link Death }
     *     
     */
    public void setDeath(Death value) {
        this.death = value;
    }

    /**
     * Gets the value of the payerPlanPeriod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payerPlanPeriod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayerPlanPeriod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PayerPlanPeriod }
     * 
     * 
     */
    public List<PayerPlanPeriod> getPayerPlanPeriod() {
        if (payerPlanPeriod == null) {
            payerPlanPeriod = new ArrayList<PayerPlanPeriod>();
        }
        return this.payerPlanPeriod;
    }

}
